In [48]:
import pandas as pd;
from glob import glob;

In [49]:
single_file_acc=pd.read_csv("../..//data/raw/metamotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [50]:
single_file_acc

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094
...,...,...,...,...,...,...
201,1547219424511,2019-01-11T16:10:24.511,16.08,0.027,0.970,-0.091
202,1547219424591,2019-01-11T16:10:24.591,16.16,0.010,0.990,-0.068
203,1547219424671,2019-01-11T16:10:24.671,16.24,0.011,0.978,-0.091
204,1547219424751,2019-01-11T16:10:24.751,16.32,0.008,0.937,-0.085
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108

In [51]:
single_file_gyr=pd.read_csv("../..//data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

In [52]:
single_file_gyr

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s)
0,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841
1,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610
2,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024
3,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634
4,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500
...,...,...,...,...,...,...
409,1547219424711,2019-01-11T16:10:24.711,16.36,2.195,-1.402,4.268
410,1547219424751,2019-01-11T16:10:24.751,16.40,4.451,-1.220,0.244
411,1547219424791,2019-01-11T16:10:24.791,16.44,7.195,-4.329,6.524
412,1547219424831,2019-01-11T16:10:24.831,16.48,8.963,-1.037,-0.366
413,1547219424871,2019-01-11T16:10:24.871,16.52,-3.476,2.134,-5.305

In [53]:
files = glob("../..//data/raw/MetaMotion/MetaMotion/*.csv")
files

['../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.38.54.580_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.41.24.439_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy3-rpe7_MetaWear_2019-01-11T16.44.00.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.49.46.484_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.53.06.282_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-heavy_MetaWear_2019-01-14T14.55.42.246_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-medium1-rpe7_MetaWear_2019-01-11T16.53.53.376_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-medium2-rpe7_MetaWear_2019-01-11T16.57.30.113_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-ohp-medium3-rpe7_MetaWear_2019-01-11T17.00.49.801_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-sitting_MetaWear_2019-01-18T18.22.25.565_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-rest-standing_MetaWear_2019-01-18T18.25.39.382_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-row-heavy_MetaWear_2019-01-14T15.06.50.281_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.04.08.637_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.09.06.903_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-heavy_MetaWear_2019-01-15T20.14.03.633_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-medium1-rpe7_MetaWear_2019-01-11T17.05.44.498_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-medium2-rpe8_MetaWear_2019-01-11T17.17.15.443_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\A-squat-medium3-rpe7_MetaWear_2019-01-11T17.19.34.896_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-bench-heavy1-rpe8_MetaWear_2019-01-11T16.08.04.758_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-bench-heavy2-rpe8_MetaWear_2019-01-11T16.12.04.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-heavy1-rpe8_MetaWear_2019-01-11T16.40.07.902_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-heavy2-rpe7_MetaWear_2019-01-11T16.42.43.398_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-heavy3-rpe8_MetaWear_2019-01-11T16.45.55.708_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-medium1-rpe8_MetaWear_2019-01-11T16.48.54.290_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-medium2-rpe8_MetaWear_2019-01-11T16.55.53.154_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-ohp-medium3-rpe9_MetaWear_2019-01-11T16.59.28.181_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\B-squat-medium1-rpe9_MetaWear_2019-01-11T17.09.32.694_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-bench-heavy1_MetaWear_2019-01-14T14.29.37.418_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-bench-heavy2_MetaWear_2019-01-14T14.32.11.392_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-bench-heavy_MetaWear_2019-01-14T14.51.27.130_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.32.32.136_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-dead-medium_MetaWear_2019-01-15T20.37.17.794_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.54.34.321_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-ohp-heavy_MetaWear_2019-01-14T14.57.26.702_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.05.36.986_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-heavy_MetaWear_2019-01-14T15.08.50.111_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Accelerometer_12.500Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-row-medium_MetaWear_2019-01-14T15.01.39.689_C42732BE255C_Gyroscope_25.000Hz_1.4.41.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.06.31.280_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.11.55.634_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\C-squat-heavy_MetaWear_2019-01-15T20.17.27.856_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.30.48.777_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.33.07.895_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-row-medium_MetaWear_2019-01-18T18.34.52.516_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-squat-heavy_MetaWear_2019-01-18T18.03.51.096_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.45.47.575_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\D-squat-medium_MetaWear_2019-01-18T17.51.40.910_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy2_MetaWear_2019-01-14T14.27.00.784_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy3-rpe8_MetaWear_2019-01-11T16.14.45.178_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.12.13.952_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.21.29.033_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-bench-medium_MetaWear_2019-01-18T18.24.19.109_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-dead-heavy_MetaWear_2019-01-15T20.35.27.174_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-dead-medium1-rpe6_MetaWear_2019-01-11T17.24.24.832_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv',
 '../..//data/raw/MetaMotion/MetaMotion\\E-dead-medium_MetaWear_2019-01-15T20.26.26.347_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv',

In [54]:
len(files)

187

NOW I AM GOING TO EXRACT FEATURES FROM CSV FILES

In [55]:
f=files[0]
f

'../..//data/raw/MetaMotion/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv'

In [56]:
f.split("-") # i am using this to extract features from the name of data.

['../..//data/raw/MetaMotion/MetaMotion\\A',
 'bench',
 'heavy2',
 'rpe8_MetaWear_2019',
 '01',
 '11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv']

In [57]:
datapath=("../..//data/raw/MetaMotion/MetaMotion\\")

In [58]:
participant=f.split("-")[0].replace(datapath,"")
label=f.split("-")[1]
category=f.split("-")[2].rstrip("123")
category

'heavy'

In [59]:
df=pd.read_csv(f)
df["participant"]=participant
df["label"]=label
df["category"]=category

In [60]:
df 
#so know as we can see that it works and we successfully 
#created new features. now we are going to add this to whole data by looping throught it

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy
...,...,...,...,...,...,...,...,...,...
201,1547219424511,2019-01-11T16:10:24.511,16.08,0.027,0.970,-0.091,A,bench,heavy
202,1547219424591,2019-01-11T16:10:24.591,16.16,0.010,0.990,-0.068,A,bench,heavy
203,1547219424671,2019-01-11T16:10:24.671,16.24,0.011,0.978,-0.091,A,bench,heavy
204,1547219424751,2019-01-11T16:10:24.751,16.32,0.008,0.937,-0.085,A,bench,heavy
205,1547219424831,2019-01-11T16:10:24.831,16.40,0.021,0.966,-0.108,A,bench,heavy

In [61]:
acc_df=pd.DataFrame()
gyr_df=pd.DataFrame()

acc_set=1
gyr_set=1
for f in files:
    participant=f.split("-")[0].replace(datapath,"")
    label=f.split("-")[1]
    category=f.split("-")[2].rstrip("123_MetaWear_2019")
    df=pd.read_csv(f)

    df["participant"]=participant
    df["label"]=label
    df["category"]=category

    if"Accelerometer" in f:
        df["set"]=acc_set
        acc_set+=1 #we added set to access the data more easiely and efficiently
        acc_df=pd.concat([acc_df,df])
    if"Gyroscope" in f:
        df["set"]=gyr_set
        gyr_set+=1
        gyr_df = pd.concat([gyr_df,df])

In [62]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
237,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
238,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
239,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
240,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
241,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [63]:
gyr_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
0,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841,A,bench,heavy,1
1,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610,A,bench,heavy,1
2,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024,A,bench,heavy,1
3,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634,A,bench,heavy,1
4,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
487,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,E,squat,heavy,93
488,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,E,squat,heavy,93
489,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,E,squat,heavy,93
490,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,E,squat,heavy,93
491,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,E,squat,heavy,93

In [64]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [65]:
# # as we are able to see that time is treated as 
# # object for now so we have to convert to date time format or data type so that we are able to perform tasks on it.
acc_df.index=pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
gyr_df.index=pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

In [66]:
del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]
del gyr_df["elapsed (s)"]

del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]

In [67]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [68]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [69]:
# so now we are going to create a single function to process each and every thing

In [70]:
files=glob("../..//data/raw/MetaMotion/MetaMotion/*.csv")
def read_data_from_files(files):
    acc_df=pd.DataFrame()
    gyr_df=pd.DataFrame()

    acc_set=1
    gyr_set=1
    for f in files:
        participant=f.split("-")[0].replace(datapath,"")
        label=f.split("-")[1]
        category=f.split("-")[2].rstrip("123_MetaWear_2019")
        df=pd.read_csv(f)

        df["participant"]=participant
        df["label"]=label
        df["category"]=category

        if"Accelerometer" in f:
          df["set"]=acc_set
          acc_set+=1 #we added set to access the data more easiely and efficiently
          acc_df=pd.concat([acc_df,df])
        if"Gyroscope" in f:
            df["set"]=gyr_set
            gyr_set+=1
            gyr_df = pd.concat([gyr_df,df])

    # as we are able to see that time is treated as 
    # object for now so we have to convert to date time format or data type so that we are able to perform tasks on it.
    acc_df.index=pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
    gyr_df.index=pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")
    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]
    del gyr_df["elapsed (s)"]

    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]
    del acc_df["elapsed (s)"]  
    return acc_df,gyr_df;

In [71]:
acc_df,gyr_df = read_data_from_files(files)
acc_df,gyr_df

(                         x-axis (g)  y-axis (g)  z-axis (g) participant  \
 epoch (ms)
 2019-01-11 15:10:08.431       0.010       0.964      -0.087           A
 2019-01-11 15:10:08.511       0.000       0.961      -0.069           A
 2019-01-11 15:10:08.591       0.001       0.974      -0.087           A
 2019-01-11 15:10:08.671      -0.012       0.971      -0.084           A
 2019-01-11 15:10:08.751      -0.013       0.954      -0.094           A
 ...                             ...         ...         ...         ...
 2019-01-16 19:14:23.089       0.012       0.596       0.815           E
 2019-01-16 19:14:23.169       0.009       0.528       0.821           E
 2019-01-16 19:14:23.249       0.015       0.554       0.746           E
 2019-01-16 19:14:23.329       0.006       0.574       0.824           E
 2019-01-16 19:14:23.409       0.015       0.588       0.826           E

                          label category  set
 epoch (ms)
 2019-01-11 15:10:08.431  bench    heavy    1
 2019-01-11 15:10:08.511  bench    heavy    1
 2019-01-11 15:10:08.591  bench    heavy    1
 2019-01-11 15:10:08.671  bench    heavy    1
 2019-01-11 15:10:08.751  bench    heavy    1
 ...                        ...      ...  ...
 2019-01-16 19:14:23.089  squat    heavy   94
 2019-01-16 19:14:23.169  squat    heavy   94
 2019-01-16 19:14:23.249  squat    heavy   94
 2019-01-16 19:14:23.329  squat    heavy   94
 2019-01-16 19:14:23.409  squat    heavy   94

 [23578 rows x 7 columns],
                          x-axis (deg/s)  y-axis (deg/s)  z-axis (deg/s)  \
 epoch (ms)
 2019-01-11 15:10:08.351           0.122          -5.488          -3.841
 2019-01-11 15:10:08.391           2.195          -9.695          -0.610
 2019-01-11 15:10:08.431           2.622          -8.110          -4.024
 2019-01-11 15:10:08.471           1.951          -4.695          -4.634
 2019-01-11 15:10:08.511           1.524          -2.561          -2.500
 ...                                 ...             ...             ...
 2019-01-16 19:14:23.314          -1.707          -0.671           1.585
 2019-01-16 19:14:23.354           0.915           0.305           2.988
 2019-01-16 19:14:23.394           5.854          -2.561           1.463
 2019-01-16 19:14:23.434           4.268           0.549          -0.305
 2019-01-16 19:14:23.474          -1.098           1.768          -0.122

                         participant  label category  set
 epoch (ms)
 2019-01-11 15:10:08.351           A  bench    heavy    1
 2019-01-11 15:10:08.391           A  bench    heavy    1
 2019-01-11 15:10:08.431           A  bench    heavy    1
 2019-01-11 15:10:08.471           A  bench    heavy    1
 2019-01-11 15:10:08.511           A  bench    heavy    1
 ...                             ...    ...      ...  ...
 2019-01-16 19:14:23.314           E  squat    heavy   93
 2019-01-16 19:14:23.354           E  squat    heavy   93
 2019-01-16 19:14:23.394           E  squat    heavy   93
 2019-01-16 19:14:23.434           E  squat    heavy   93
 2019-01-16 19:14:23.474           E  squat    heavy   93

 [47218 rows x 7 columns])

In [72]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [73]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [74]:
#know the goal is to merge the data set 
data_merged=pd.concat([acc_df.iloc[:,:3],gyr_df],axis=1)

In [75]:
data_merged
#as we are able to see that gyroscope has more frequently took reading so it means gyroscope has more number of data per unit time.
#

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
data_merged.columns=[
    "acc_x",
    "acc_y",
    "acc_z",
    "gyr_x",
    "gyr_y",
    "gyr_z",
    "participant",
    "label",
    "category",
    "set"
]
data_merged

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
sampling={
    "acc_x": "mean",
    "acc_y": "mean",
    "acc_z": "mean",
    "gyr_x": "mean",
    "gyr_y": "mean",
    "gyr_z": "mean",
    "participant": "last",
    "label": "last",
    "category": "last",
    "set": "last" 
}
data_merged[:1000].resample(rule="200ms").apply(sampling)

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,B,bench,heavy,30.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,B,bench,heavy,30.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,A,bench,heavy,1.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,A,bench,heavy,1.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,A,bench,heavy,1.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,A,bench,heavy,1.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,A,bench,heavy,1.0

In [96]:
days=[g for n,g in data_merged.groupby(pd.Grouper(freq="D"))]
days[5]

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-16 14:04:06.332,NaN,NaN,NaN,1.402,-6.280,1.585,E,row,heavy,84.0
2019-01-16 14:04:06.372,NaN,NaN,NaN,1.341,-5.427,0.915,E,row,heavy,84.0
2019-01-16 14:04:06.412,NaN,NaN,NaN,-1.280,0.671,-1.829,E,row,heavy,84.0
2019-01-16 14:04:06.452,NaN,NaN,NaN,-1.829,0.366,-0.549,E,row,heavy,84.0
2019-01-16 14:04:06.492,NaN,NaN,NaN,-1.951,-2.683,1.829,E,row,heavy,84.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-16 19:35:43.646,NaN,NaN,NaN,5.671,-1.463,10.183,E,dead,heavy,72.0
2019-01-16 19:35:43.652,-0.024,-1.044,-0.172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-16 19:35:43.686,NaN,NaN,NaN,5.854,-2.988,9.512,E,dead,heavy,72.0
2019-01-16 19:35:43.726,NaN,NaN,NaN,0.915,-5.793,9.634,E,dead,heavy,72.0
2019-01-16 19:35:43.732,-0.012,-1.048,-0.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
data_resample=pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])

In [98]:
data_resample

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.8904,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.6826,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.5608,-0.2560,-1.4146,B,bench,heavy,30.0
2019-01-11 15:08:05.800,-0.024000,0.957000,-0.073500,8.0610,-4.5244,-2.0730,B,bench,heavy,30.0
2019-01-11 15:08:06.000,-0.028000,0.957667,-0.115000,2.4390,-1.5486,-3.6098,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:33:27.000,-0.048000,-1.041500,-0.076500,1.4146,-5.6218,0.2926,E,row,medium,90.0
2019-01-20 17:33:27.200,-0.037000,-1.030333,-0.053333,-2.7684,-0.5854,2.2440,E,row,medium,90.0
2019-01-20 17:33:27.400,-0.060000,-1.031000,-0.082000,2.8416,-5.1342,-0.1220,E,row,medium,90.0
2019-01-20 17:33:27.600,-0.038667,-1.025667,-0.044667,-0.2318,0.2562,1.1220,E,row,medium,90.0
2019-01-20 17:33:27.800,-0.044000,-1.034000,-0.059000,1.0980,-4.0240,0.9760,E,row,medium,90.0

In [99]:
data_resample.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   float64
dtypes: float64(7), object(3)
memory usage: 774.2+ KB

In [100]:
data_resample["set"]=data_resample["set"].astype("int")

In [101]:
data_resample.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   int32
dtypes: float64(6), int32(1), object(3)
memory usage: 739.0+ KB

In [102]:
#now we are going to export that data to interim file in data folder

In [106]:
data_resample.to_pickle("../..//data/interim/01_data_proccesed.pkl")